name: Flutter CI/CD (Android + Release)

on:
  push:
    branches: [ main ]
    tags:
      - "v*"        # v1.0.0 jaisi tag par release banega
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build Android (APK & AAB)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # (Optional) Pub cache fast builds ke liye
      - name: Cache Flutter pub
        uses: actions/cache@v4
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'   # latest stable version

      - name: Flutter doctor (info)
        run: flutter doctor -v

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze
        run: flutter analyze

      - name: Test
        run: flutter test

      - name: Build APK (release)
        run: flutter build apk --release

      - name: Build App Bundle (release)
        run: flutter build appbundle --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
          if-no-files-found: error
          retention-days: 7

      - name: Upload AAB artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-aab
          path: build/app/outputs/bundle/release/app-release.aab
          if-no-files-found: error
          retention-days: 7

  release:
    name: Create GitHub Release (on tag)
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Download APK
        uses: actions/download-artifact@v4
        with:
          name: app-release-apk
          path: ./dist

      - name: Download AAB
        uses: actions/download-artifact@v4
        with:
          name: app-release-aab
          path: ./dist

      - name: Create Release & Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/app-release.apk
            dist/app-release.aab
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
